name: Test schedule

on:
  workflow_dispatch:

  push:
    paths:
      - "test-schedule.yml"

  schedule:
    - cron: "15 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hola
        run: echo "HOLA - el schedule funciona"
